### PR TITLE
Fix bugs with Global achievements

### PR DESCRIPTION
**Pull request by NerdyChara**
These are modifications I've made designed to get everything to work nicely. My global achievements were stuck at 99% and never unlocking. Then when they unlocked, the data was never actually saved to a file.

### CODE REVIEW

**Comment by SMO-Valadorn** [comment]
Yo, 
Thanks for your contribution!
I changed quite a lot of the code already, but I'll add some of the changes I see here too, thanks again :)

**Comment by NerdyChara** [comment]
I have some more changes btw. And a typescript definition file started if you like. And a somewhat controversial change I want to propose for Global Achievements. Can we migrate the Achievements file location to the saves folder? So on load if the Achievements.json is in the save folder load that one. Then on save if the old file exists; erase it and save the new one. Also how do we plan on supporting say Mac or Linux too?

**Comment by SMO-Valadorn** [comment]
**About the new changes**
Looking good, I'll implement some of these new changes too. 

**About the d.t.s. file**
I don't have much knowledge in programming (I'm a chemistry student) so I'm not sure on what a "typescript definition file" is and I don't know how to use it but I'll definitely study that, it's always good to learn new stuff. 

**About movng the json file & Compatibility with Mac and Linux**
I'm willing to inherit RPGMaker's file save methods (using the StorageManager), this way global achievs should also work on browser, I'm not sure how to support Mac or Linux though, hopefully this change will help with that.

**Comment by NerdyChara** [comment]
Okay so a .d.ts file is used by Visual Studio Code to provide intellisense (By that I mean it provides popup details when you mouse over a property name). Nobody in the RPG Maker MV community seems to do it. But as someone with an Associate's degree in Computer Science, I tend to want to have every possible method typed to reduce errors. The module.exports thing is related to the Floss testing system that I was trying to integrate with a game I was working on. My integration tests seem good. (which it seeming no one else in the MV and MZ community is using; maybe because of base code modifications)

**Comment by NerdyChara** [comment]
A screenshot of the testing system in action. Capture

**Comment by NerdyChara** [comment]
Here we are. I believe it works fine the way I set it up with global achievements. Plus I removed the stuff in the code that nobody besides me seems to use.

**Pull request closed without merging**
